INSERT INTO public.topics VALUES (60, 1, 'Вероятность и статистика') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (60, 2, 'Алгебраические выражения. Степени и корни') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (60, 3, 'Анализ геометрических высказываний') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (57, 4, 'Расчёты по формулам') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (60, 5, 'Практические расчетные задачи') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (60, 6, 'Неравенства, координатная прямая') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (59, 7, 'Уравнения и системы уравнений (1 часть)') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (60, 8, 'Графики функций') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (60, 9, 'Неравенства и системы неравенств (1 часть)') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (60, 10, 'Вычисления и преобразования') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (60, 11, 'Алгебраические выражения. Формулы сокращённого умножения') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (53, 12, 'Прогрессии') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (57, 13, 'Треугольники') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (48, 14, 'Прямоугольный треугольник') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (54, 15, 'Четырехугольники') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (60, 16, 'Окружность') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (60, 17, 'Площади фигур') ON CONFLICT DO NOTHING;
INSERT INTO public.topics VALUES (60, 18, 'Фигуры на квадратной решетки') ON CONFLICT DO NOTHING;